# Generated by Django 5.0.6 on 2024-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistration', '0003_remove_customuser_email_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
